name: Build Image

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
#  workflow_dispatch:
    
jobs:
  clone_repo:
    name: Clone repo
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3  
        
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: clone_repo
    
    steps:
      - name: Update apt
        run: sudo apt update

      - name: Install debootstrap
        run: sudo apt install -y debootstrap

      - name: Install snapd
        run: sudo apt install -y snapd

      - name: Install distrobuilder
        run: sudo snap install distrobuilder --classic
        
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Build Image
        run: sudo distrobuilder -o image.architecture=amd64 -o image.release=jammy build-lxc ubuntu.yaml 
        
      - name: List files
        run: sudo ls -alh 
        
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: image-${{ env.os }}-lxc
          path: |
            ./*.xz
