name: Build Image

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Update apt
        run: sudo apt update
        
      - name: Install dependencies
        run: sudo apt install -y golang-go debootstrap rsync gpg squashfs-tools git
        
      - name: Install distrobuilder
        run: git clone https://github.com/lxc/distrobuilder && cd ./distrobuilder && make && cd ..
        
      - name: Build Image
        run: sudo $HOME/go/bin/distrobuilder build-lxc ubuntu.yaml

      - name: List files
        run: sudo ls -alh

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./rootfs.tar.xz
            ./meta.tar.xz
