name: Self

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: APT Update
      run: sudo apt update
      
    - name: Install debootstrap
      run: sudo apt install -y debootstrap
      
    - name: Install snapd
      run: sudo apt install -y snapd
      
    - name: Install distrobuilder
      run: sudo snap install distrobuilder --classic
    
    - name: List files
      run: sudo ls /usr/share/debootstrap/scripts
      
    - name: Build Image
      run: sudo distrobuilder -o image.architecture=amd64 -o image.release=buster build-lxc ubuntu.yaml 
