name: Build Image

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Update apt
        run: sudo apt update

      - name: Install debootstrap
        run: sudo apt install -y debootstrap

      - name: Install snapd
        run: sudo apt install -y snapd

      - name: Install distrobuilder
        run: sudo snap install distrobuilder --classic

      - name: Build Image
        run: sudo distrobuilder -o image.architecture=amd64 -o image.release=jammy build-lxc ubuntu.yaml

      - name: List files
        run: sudo ls -alh

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./rootfs.tar.xz
            ./meta.tar.xz
