name: Self

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install snapd
      run: sudo apt update && sudo apt install -y snapd
      
    - name: install distrobuilder
      run: sudo snap install distrobuilder --classic
  
    - name: build lxc container
      run: sudo distrobuilder build-lxc mageia.yaml 
