name: Build Image

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Golnag
        run: wget https://go.dev/dl/go1.21.1.linux-amd64.tar.gz && sudo tar -xf go1.21.1.linux-amd64.tar.gz -C /usr/local && export PATH=$PATH:/usr/local.go/bin && go version

      - name: Update apt
        run: sudo apt update
        
      - name: Install dependencies
        run: sudo apt install -y debootstrap rsync gpg squashfs-tools git

      - name: Install distrobuilder
        run: git clone https://github.com/lxc/distrobuilder && cd ./distrobuilder && make && cd ..

      - name: Build Image
        run: sudo $HOME/go/bin/distrobuilder build-lxd ubuntu.yaml
        
      - name: Tar metadata
        run: sudo tar -cvzf metadata.tar.gz metadata.yaml

      - name: List files
        run: sudo ls -alh

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./*.xz
            ./*.tar
            ./*.gz

